### ISSUE TITLE
Wallet not working on macOS High Sierra. "High Sierra not supported with this build"

### ISSUE THREAD

**Issue by whatevercode** [hempcoin-project/hempcoin#2]
On macOS High Sierra i get is error message on starting the QT wallet. 
<img width="389" alt="screen shot 2018-06-23 at 20 47 10" src="https://user-images.githubusercontent.com/1756595/41932049-2f5221c4-7980-11e8-8998-e027db454e02.png">

The cli wallet is working fine. On macOS Sierra the QT wallet is working fin.

**Comment by hempcoin-project** [comment]
An updated wallet for High Sierra will be released soon!

**Comment by mo-bay** [comment]
Thank you for providing us with the High Sierra binary @whatevercode. Closing this issue now!
